import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Función para generar slug
function generateSlug(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

// URLs de imágenes por categoría (URLs estables de Unsplash)
const categoryImages: Record<string, string> = {
  'WHISKY': 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&q=80',
  'RON': 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=800&q=80',
  'TEQUILA': 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800&q=80',
  'MEZCAL': 'https://images.unsplash.com/photo-1598155523122-38423bb4d6c1?w=800&q=80',
  'GIN': 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
  'VODKA': 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
  'LICOR': 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800&q=80',
  'VERMOUTH': 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=800&q=80',
  'VINOS ESPUMOSOS': 'https://images.unsplash.com/photo-1594916383637-8a0b1f0c0b1f?w=800&q=80',
  'VINO': 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
  'PREMEZCLADO': 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80',
};

async function main() {
  console.log(' Starting seed...');

  // Limpiar datos existentes
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.inventoryReservation.deleteMany();
  await prisma.product.deleteMany();
  await prisma.user.deleteMany();

  console.log('🗑️  Cleaned existing data');

  // Catálogo completo de productos con imágenes
  const products = [
    // WHISKY
    {
      name: 'WHISKY MACALLAN RARE CASK',
      brand: 'The Macallan',
      category: 'WHISKY',
      description: 'The Macallan Rare Cask es el whisky más completo jamás creado por The Macallan. Se usan 16 diferentes tipos de barricas 100% Ex-Jerez. Tiene suaves notas a vainilla y uvas abriendo paso a una dulce combinación de manzana, limón y naranja. Todo ello equilibrado gracias a un exquisito cuarteto de especias: jengibre, canela, nuez moscada y clavo.',
      presentation: '700 ml',
      alcoholicDegree: 43,
      price: 8500.00,
      currency: 'MXN',
      stock: 50,
      country: 'Escocia',
      region: 'Speyside',
      tastingNotes: ['vainilla', 'uvas', 'manzana', 'limón', 'naranja', 'jengibre', 'canela', 'nuez moscada', 'clavo'],
    },
    {
      name: 'WHISKY MACALLAN DOUBLE CASK 18 AÑOS',
      brand: 'The Macallan',
      category: 'WHISKY',
      description: 'Un whisky de malta único perfectamente equilibrado madurado durante 18 años en barricas de roble americano y europeo que previamente han contenido Jerez. El roble americano condimentado con jerez añade una delicada vainilla a la sutil especia del roble europeo, entregando un whisky con un sabor y carácter más dulce y cálido.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 12500.00,
      currency: 'MXN',
      stock: 30,
      country: 'Escocia',
      region: 'Speyside',
      tastingNotes: ['vainilla', 'especias', 'dulce', 'cálido'],
    },
    {
      name: 'WHISKY MACALLAN DOUBLE CASK 15 AÑOS',
      brand: 'The Macallan',
      category: 'WHISKY',
      description: 'Un whisky envejecido durante 15 años en dos tipos de roble, en barricas artesanales especialmente seleccionadas y aderezadas con jerez Oloroso seco. El roble americano aporta delicados sabores a vainilla, cítricos y caramelo.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 9800.00,
      currency: 'MXN',
      stock: 40,
      country: 'Escocia',
      region: 'Speyside',
      tastingNotes: ['vainilla', 'cítricos', 'caramelo'],
    },
    {
      name: 'WHISKY MACALLAN DOUBLE CASK 12 AÑOS',
      brand: 'The Macallan',
      category: 'WHISKY',
      description: 'Un whisky envejecido durante 12 años en dos tipos de barrica de roble americano y europeo sazonadas con jerez oloroso para crear el carácter acogedor y distintivo de este armonioso single malt. Este whisky posee un sabor meloso a madera, especias y cítricos, en balance con toques a pasas y caramelo.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 7200.00,
      currency: 'MXN',
      stock: 60,
      country: 'Escocia',
      region: 'Speyside',
      tastingNotes: ['madera', 'especias', 'cítricos', 'pasas', 'caramelo', 'manzana', 'naranja', 'vainilla'],
    },
    {
      name: 'WHISKY MACALLAN TRIPLE CASK 12 AÑOS',
      brand: 'The Macallan',
      category: 'WHISKY',
      description: 'Este whisky tiene una maduración de un mínimo de 12 años en tres tipos de barricas de roble. Esta compleja combinación ofrece un whisky suave con notas de frutas secas, miel y especias.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 6500.00,
      currency: 'MXN',
      stock: 70,
      country: 'Escocia',
      region: 'Speyside',
      tastingNotes: ['frutas secas', 'miel', 'especias'],
    },
    {
      name: 'WHISKY MACALLAN SHERRY OAK CASK 12 AÑOS',
      brand: 'The Macallan',
      category: 'WHISKY',
      description: 'Destilado en alambiques de cobre de pequeñas dimensiones al inconfundible estilo escocés. Después madura en barricas de roble americano que albergaron vinos de Jerez. Muestra intensas notas de frutas secas y especias transmitidas por la madera.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 7800.00,
      currency: 'MXN',
      stock: 45,
      country: 'Escocia',
      region: 'Speyside',
      tastingNotes: ['frutas secas', 'especias', 'madera'],
    },
    {
      name: 'WHISKY HIGHLAND PARK 12',
      brand: 'Highland Park',
      category: 'WHISKY',
      description: 'Whisky elaborado con una cuidada selección de cebadas malteadas y mezcladas con agua de la fuente del Cattie Maggie. Esta malta se añeja en barricas durante doce años como mínimo, tiempo necesario para darle su característico sabor afinado y su color ámbar brillante.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 2800.00,
      currency: 'MXN',
      stock: 80,
      country: 'Escocia',
      region: 'Orkney',
      tastingNotes: ['ahumado', 'dulce', 'rosas', 'vainilla', 'almíbar', 'madera'],
    },
    {
      name: 'WHISKY OLD SMUGGLER',
      brand: 'Old Smuggler',
      category: 'WHISKY',
      description: 'Whisky escocés con notas ahumadas y dulces en su sabor, con un final aterciopelado y persistente. Su aroma a rosas, vainilla, almíbar y madera, es complejo y equilibrado.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 1200.00,
      currency: 'MXN',
      stock: 100,
      country: 'Escocia',
      tastingNotes: ['ahumado', 'dulce', 'vainilla'],
    },
    {
      name: 'BOURBON WHISKEY WILD TURKEY 101 PROOF',
      brand: 'Wild Turkey',
      category: 'WHISKY',
      description: 'Es un bourbon estadounidense de alta calidad, conocido por su robusto sabor y alto contenido de alcohol (50.5% ABV). Elaborado en Kentucky, este bourbon se destila a partir de una mezcla de maíz, centeno y malta de cebada, y se envejece 8 años en barricas de roble carbonizadas. Destacan sus notas de caramelo, vainilla y roble.',
      presentation: '750 ml',
      alcoholicDegree: 50.5,
      price: 1800.00,
      currency: 'MXN',
      stock: 60,
      country: 'Estados Unidos',
      region: 'Kentucky',
      tastingNotes: ['caramelo', 'vainilla', 'roble'],
    },
    {
      name: 'BOURBON WHISKEY WILD TURKEY 81 PROOF',
      brand: 'Wild Turkey',
      category: 'WHISKY',
      description: 'Wild Turkey es un bourbon elaborado en Kentucky, Estados Unidos. Es un bourbon envejecido en barricas de roble blanco americano. Tiene notas a vainilla, pera y toques de especias.',
      presentation: '750 ml',
      alcoholicDegree: 40.5,
      price: 1500.00,
      currency: 'MXN',
      stock: 70,
      country: 'Estados Unidos',
      region: 'Kentucky',
      tastingNotes: ['vainilla', 'pera', 'especias'],
    },
    {
      name: 'BOURBON WHISKEY WILD TURKEY AMERICAN HONEY',
      brand: 'Wild Turkey',
      category: 'WHISKY',
      description: 'Es un bourbon whiskey excepcionalmente suave, hecho a base de Wild Turkey 40° mezclado con miel pura. En boca tiene notas a miel, caramelo y naranja.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 1600.00,
      currency: 'MXN',
      stock: 65,
      country: 'Estados Unidos',
      region: 'Kentucky',
      tastingNotes: ['miel', 'caramelo', 'naranja'],
    },

    // RON
    {
      name: 'RON CENTENARIO 30 AÑOS EDICION LIMITADA',
      brand: 'Centenario',
      category: 'RON',
      description: 'La máxima expresión del Ron Centenario, intensamente aromático, este ron es audaz, cremoso y sedoso. Añejado en barricas de roble blanco americano. Ron Centenario 30 tiene un color Oro intenso, tiene un aroma a chocolate, frutas maduras, cuero, brandi, y especias. Tiene un sabor especiado y afrutado.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 4500.00,
      currency: 'MXN',
      stock: 25,
      country: 'Costa Rica',
      tastingNotes: ['chocolate', 'frutas maduras', 'cuero', 'brandi', 'especias'],
    },
    {
      name: 'RON CENTENARIO 25 AÑOS GRAN RESERVA',
      brand: 'Centenario',
      category: 'RON',
      description: 'Ron añejado en un sistema solera con barricas de roble blanco americano que solían contener principalmente whisky de las tierras bajas de escocia. Ron Centenario 25 tiene un color ámbar oro y un aroma a jengibre, manzana verde, caramelo y un sabor a pimienta, zumo de limón, y un toque ahumado.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 3800.00,
      currency: 'MXN',
      stock: 30,
      country: 'Costa Rica',
      tastingNotes: ['jengibre', 'manzana verde', 'caramelo', 'pimienta', 'limón', 'ahumado'],
    },
    {
      name: 'RON CENTENARIO 20 AÑOS FUNDACION',
      brand: 'Centenario',
      category: 'RON',
      description: 'Ron añejado en barricas de roble blanco americano. Tiene un color ámbar con un aroma a vainilla con toques de fruta madura, manzana y cereza. Tiene un sabor dulce y agradable con una notable intensidad aromática. Tiene un conjunto muy armonioso de notas de vainilla y frutas exóticas (piña).',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 3200.00,
      currency: 'MXN',
      stock: 40,
      country: 'Costa Rica',
      tastingNotes: ['vainilla', 'fruta madura', 'manzana', 'cereza', 'piña'],
    },
    {
      name: 'RON CENTENARIO 12 AÑOS GRAN LEGADO',
      brand: 'Centenario',
      category: 'RON',
      description: 'Ron añejado en barricas de roble blanco americano, que su primer uso añejaron whisky escocés de las tierras altas y bajas. Centenario 12 tiene un color ámbar con aromas a manzana, cereza, chocolate con leche, caramelo y vainilla. Tiene un sabor cremoso con frutos rojos, pasas y caramelo.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 2400.00,
      currency: 'MXN',
      stock: 50,
      country: 'Costa Rica',
      tastingNotes: ['manzana', 'cereza', 'chocolate', 'caramelo', 'vainilla', 'frutos rojos', 'pasas'],
    },
    {
      name: 'RON CENTENARIO 9 AÑOS CONMEMORATIVO',
      brand: 'Centenario',
      category: 'RON',
      description: 'Ron Centenario Conmemorativo 9 años es una gota especial, almacenada durante 9 años en exquisitas barricas de roble a 1200 m de altitud, con el clima tropical de Costa Rica. En el paladar, le espera una impresionante combinación de aromas de vainilla, miel y pasas. En el final, es ligeramente picante con un sabor dulce de cacao.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 1900.00,
      currency: 'MXN',
      stock: 60,
      country: 'Costa Rica',
      tastingNotes: ['vainilla', 'miel', 'pasas', 'cacao', 'picante'],
    },
    {
      name: 'RON CENTENARIO 7 AÑOS AÑEJO ESPECIAL',
      brand: 'Centenario',
      category: 'RON',
      description: 'Una mezcla brillante y frutal de rones añejados en barricas de roble blanco americano, que su primer uso añejaron whisky escocés de highland y lowlands. Centenario 7 tiene un color oro, con aroma a miel, manzana roja y madera y su sabor es ahumado y amaderado con toques a miel y frutas.',
      presentation: '750 ml',
      alcoholicDegree: 35,
      price: 1500.00,
      currency: 'MXN',
      stock: 70,
      country: 'Costa Rica',
      tastingNotes: ['miel', 'manzana roja', 'madera', 'ahumado', 'frutas'],
    },

    // TEQUILA
    {
      name: 'TEQUILA DON RAMON EDICION LIMITADA AÑEJO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un tequila añejo que se destila doblemente y se envejece en barricas de roble durante 12 meses. Elaborado 100% con Agave Azul de las tierras altas de Jalisco, México. Fresco y amaderado con elegantes notas de frutos secos y agave cocido. Notas de canela, clavo y comino.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 2200.00,
      currency: 'MXN',
      stock: 40,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['frutos secos', 'agave cocido', 'canela', 'clavo', 'comino'],
    },
    {
      name: 'TEQUILA DON RAMON EDICION LIMITADA BLANCO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un tequila doblemente destilado para un sabor suave y brillante y un perfil puro. Hecho 100% de agave azul de las tierras altas de Jalisco, México. Brillante, limpio y herbal con delicadas notas de agave. Un toque cítrico que evoluciona hacia una mineralidad cálida.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 1800.00,
      currency: 'MXN',
      stock: 50,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['agave', 'herbal', 'cítrico', 'mineral'],
    },
    {
      name: 'TEQUILA DON RAMON EDICION LIMITADA CERAMICA AÑEJO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Elaborado 100% de agave azul con cocción en hornos de mampostería. El Tequila madura en Barricas de Roble Blanco Americano 12 meses, otorgándole notas a madera y un color ámbar oscuro.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 2400.00,
      currency: 'MXN',
      stock: 35,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['madera', 'agave', 'caramelo'],
    },
    {
      name: 'TEQUILA DON RAMON ED. LIMITADA CERAMICA REPOSADO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Elaborado 100% de agave azul con cocción en hornos de mampostería. El Tequila madura en Barricas de Roble Blanco Americano 6 meses, otorgándole notas a madera y un color ámbar claro.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 2000.00,
      currency: 'MXN',
      stock: 45,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['madera', 'agave', 'vainilla'],
    },
    {
      name: 'TEQUILA DON RAMON EDICION LIMITADA CERAMICA BLANCO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Elaborado 100% de agave azul con cocción en hornos de mampostería. El líquido nítido de este espléndido perfil tiene notas dulces y de agave cocido.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 1700.00,
      currency: 'MXN',
      stock: 55,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['agave cocido', 'dulce', 'herbal'],
    },
    {
      name: 'TEQUILA DON RAMON PLATINIUM AÑEJO CRISTALINO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un tequila doblemente destilado y envejecido en barricas de roble americano durante 12 meses. Aromático y bien definido con notas a mantequilla. Un patrimonio de especias y madera, mientras que el descanso prolongado despierta las notas más profundas de nueces y vainilla.',
      presentation: '700 ml',
      alcoholicDegree: 35,
      price: 2600.00,
      currency: 'MXN',
      stock: 30,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['mantequilla', 'especias', 'madera', 'nueces', 'vainilla'],
    },
    {
      name: 'TEQUILA DON RAMON PLATINIUM REPOSADO CRISTALINO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un tequila doblemente destilado y reposado en barricas de roble americano y francés. Suave, de cuerpo medio y amaderado con notas dulces complejas. Final cítrico y herbal equilibrado.',
      presentation: '700 ml',
      alcoholicDegree: 35,
      price: 2100.00,
      currency: 'MXN',
      stock: 40,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['madera', 'dulce', 'cítrico', 'herbal'],
    },
    {
      name: 'TEQUILA DON RAMON PLATINIUM BLANCO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un tequila que se destila dos veces para obtener un gusto brillante y perfil puro. Hecho 100% de Agave azul de las tierras altas de Jalisco. Brillante, cítrico, con notas de agave.',
      presentation: '700 ml',
      alcoholicDegree: 35,
      price: 1600.00,
      currency: 'MXN',
      stock: 60,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['agave', 'cítrico', 'mineral'],
    },
    {
      name: 'TEQUILA DON RAMON PUNTA DIAMANTE AÑEJO CRISTALINO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es una expresión premium que combina la riqueza del añejamiento con la pureza del cristalino. Madurado en barricas de roble y luego filtrado para obtener una apariencia clara. Notas de agave cocido, madera envejecida, vainilla y un toque sutil de especias.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 2800.00,
      currency: 'MXN',
      stock: 25,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['agave cocido', 'madera', 'vainilla', 'especias'],
    },
    {
      name: 'TEQUILA DON RAMON PUNTA DIAMANTE REPOSADO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un tequila doblemente destilado y reposado en barricas de roble blanco. Especiado y herbáceo con una esencia de caramelo extraída del barril. Final equilibrado a base de hierbas y cítricos.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 2200.00,
      currency: 'MXN',
      stock: 35,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['especiado', 'herbáceo', 'caramelo', 'hierbas', 'cítricos'],
    },
    {
      name: 'TEQUILA DON RAMON PUNTA DIAMANTE BLANCO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un tequila de doble destilación, hecho 100% de agave azul de las tierras altas de Jalisco. Brillante, fresco y floral. Sabor herbáceo pronunciado con un toque de dulzura que evoluciona hacia una mineralidad cálida.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 1900.00,
      currency: 'MXN',
      stock: 50,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['floral', 'herbáceo', 'dulce', 'mineral'],
    },
    {
      name: 'TEQUILA DON RAMON TAMARINDO',
      brand: 'Don Ramón',
      category: 'TEQUILA',
      description: 'Es un Tequila Blanco 100% Agave. Una innovadora y vibrante variación del tequila clásico, infusionado con el distintivo sabor del tamarindo. Color cristalino y aroma a notas de tamarindo. Destellos herbales y esencia de tamarindo.',
      presentation: '750 ml',
      alcoholicDegree: 35,
      price: 1700.00,
      currency: 'MXN',
      stock: 45,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['tamarindo', 'herbal', 'agave'],
    },
    {
      name: 'TEQUILA VIUDA DE ROMERO REPOSADO',
      brand: 'Viuda de Romero',
      category: 'TEQUILA',
      description: 'Es un tequila nacido en el año de 1852. Tequila reposado de color transparente y brillante, con tonos dorados, con olor floral con notas de canela, vainilla, piña y un toque de madera. Sabor especioso, ahumado con toques de piña, plátano y canela.',
      presentation: '1000 ml',
      alcoholicDegree: 35,
      price: 1400.00,
      currency: 'MXN',
      stock: 60,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['floral', 'canela', 'vainilla', 'piña', 'madera', 'ahumado', 'plátano'],
    },
    {
      name: 'TEQUILA VIUDA DE ROMERO BLANCO',
      brand: 'Viuda de Romero',
      category: 'TEQUILA',
      description: 'Es un tequila nacido en el año de 1852. Tequila blanco, ideal para mezclar o tomarse solo, versátil, de un sabor distintivo.',
      presentation: '1000 ml',
      alcoholicDegree: 35,
      price: 1200.00,
      currency: 'MXN',
      stock: 70,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['agave', 'herbal', 'cítrico'],
    },
    {
      name: 'TEQUILA BUEN AMIGO GOLD',
      brand: 'Buen Amigo',
      category: 'TEQUILA',
      description: 'Es un tequila mexicano envejecido entre dos meses y un año en barricas de madera. Presenta notas de madera, vainilla, caramelo y especias.',
      presentation: '700 ml',
      alcoholicDegree: 35,
      price: 900.00,
      currency: 'MXN',
      stock: 80,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['madera', 'vainilla', 'caramelo', 'especias'],
    },
    {
      name: 'TEQUILA BUEN AMIGO SILVER',
      brand: 'Buen Amigo',
      category: 'TEQUILA',
      description: 'Es un tequila con identidad propia, elaborado de manera artesanal con agave tequilana. Presentación cristalino brillante. En el paladar, se destacan las notas a frutas cítricas y dulces.',
      presentation: '700 ml',
      alcoholicDegree: 35,
      price: 800.00,
      currency: 'MXN',
      stock: 90,
      country: 'México',
      region: 'Jalisco',
      tastingNotes: ['cítrico', 'dulce', 'agave'],
    },

    // MEZCAL
    {
      name: 'MEZCAL DON RAMON ESPADIN JOVEN',
      brand: 'Don Ramón',
      category: 'MEZCAL',
      description: 'Este mezcal está hecho con agave espadín, cosechado en una tierra privilegiada que provee el rico sabor ahumado a tierra y madera. De carácter robusto y complejo con notas ahumadas bien definidas, cárnicas y ligeramente afrutadas, contrastando con notas sutiles a tierra húmeda.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 1800.00,
      currency: 'MXN',
      stock: 40,
      country: 'México',
      region: 'Oaxaca',
      tastingNotes: ['ahumado', 'tierra', 'madera', 'cárnico', 'afrutado'],
    },

    // GIN
    {
      name: 'GIN LE TRIBUTE',
      brand: 'Le Tribute',
      category: 'GIN',
      description: 'Es una ginebra premium española y surge como homenaje al fundador de la destilería MG. El producto está creado con siete destilaciones una por cada uno de sus componentes botánicos. En boca encontramos notas cítricas junto a matices de enebro muy bien equilibrados.',
      presentation: '700 ml',
      alcoholicDegree: 43,
      price: 2200.00,
      currency: 'MXN',
      stock: 35,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['cítrico', 'enebro', 'botánicos'],
    },
    {
      name: 'LONDON DRY GIN MASTER´S',
      brand: 'Master\'s',
      category: 'GIN',
      description: 'Gin cristalino, limpio y brillante, con aroma a enebro, pino y fondo de hierbas. Es suave, de cuerpo medio y ligeramente picante. Galardonado con la Doble Medalla de Oro con el título de "Best Gin" en San Francisco World Spirits Competition 2015.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 1400.00,
      currency: 'MXN',
      stock: 50,
      country: 'España',
      tastingNotes: ['enebro', 'pino', 'hierbas', 'picante'],
    },
    {
      name: 'GIN MASTER´S PINK',
      brand: 'Master\'s',
      category: 'GIN',
      description: 'Este gin rosado se elabora con base de Master´s Gin, a la que se le añaden aromas naturales de fresa y frambuesa extraídos a partir de la maceración de frutos rojos en alcohol de cereales.',
      presentation: '700 ml',
      alcoholicDegree: 37.5,
      price: 1500.00,
      currency: 'MXN',
      stock: 45,
      country: 'España',
      tastingNotes: ['fresa', 'frambuesa', 'frutos rojos'],
    },
    {
      name: 'GIN MG',
      brand: 'MG',
      category: 'GIN',
      description: 'Ginebra bidestilada con alcohol etílico agrícola elaborada a base de la más cuidadosa selección de bayas de enebro bajo el método London Gin. Es una ginebra neutra y seca.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 1200.00,
      currency: 'MXN',
      stock: 60,
      country: 'España',
      tastingNotes: ['enebro', 'seco', 'neutro'],
    },
    {
      name: 'GIN MG ROSA',
      brand: 'MG',
      category: 'GIN',
      description: 'Gin MG Rosa es una ginebra elaborada según el método tradicional London Dry Gin. La misma base de Gin Mg, a la que se le añade un sirope de fresas elaborado con ingredientes naturales. En nariz tiene aromas a frutos rojos y cítricos. En boca es suave, dulce y refrescante.',
      presentation: '700 ml',
      alcoholicDegree: 37.5,
      price: 1300.00,
      currency: 'MXN',
      stock: 55,
      country: 'España',
      tastingNotes: ['frutos rojos', 'cítricos', 'fresa', 'dulce'],
    },

    // VODKA
    {
      name: 'VODKA STOLICHNAYA ELIT',
      brand: 'Stolichnaya',
      category: 'VODKA',
      description: 'Vodka elaborado con grano de invierno y con tres destilaciones a fuego lento. El proceso de filtrado único, por medio de congelación extrema, da como resultado un vodka con un altísimo nivel de pureza.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 2800.00,
      currency: 'MXN',
      stock: 40,
      country: 'Rusia',
      tastingNotes: ['puro', 'suave', 'limpio'],
    },
    {
      name: 'VODKA STOLICHNAYA GOLD',
      brand: 'Stolichnaya',
      category: 'VODKA',
      description: 'Vodka excepcionalmente cristalino con sutiles aromas de cáscara de cítricos y anís. Tiene una filtración a través de bobinas de hilo de oro, lo cual amplifica la profundidad, mejora la suavidad y armoniza el líquido.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 3200.00,
      currency: 'MXN',
      stock: 30,
      country: 'Rusia',
      tastingNotes: ['cítricos', 'anís', 'suave'],
    },
    {
      name: 'VODKA STOLICHNAYA PREMIUM',
      brand: 'Stolichnaya',
      category: 'VODKA',
      description: 'Vodka de origen ruso, 4 veces destilado, producido de alcohol de trigo y centeno y es 3 veces filtrado por arena de cuarzo, carbón de leña activado y tejido de paño.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 1800.00,
      currency: 'MXN',
      stock: 60,
      country: 'Rusia',
      tastingNotes: ['trigo', 'centeno', 'puro'],
    },
    {
      name: 'SKYY VODKA',
      brand: 'Skyy',
      category: 'VODKA',
      description: 'Es un vodka Premium norteamericano. Se obtiene a través de cuatro destilaciones de trigo y filtrado tres veces. Su nombre y el color de su botella es tomado del cielo de la ciudad de San Francisco.',
      presentation: '750 ml',
      alcoholicDegree: 40,
      price: 1600.00,
      currency: 'MXN',
      stock: 70,
      country: 'Estados Unidos',
      region: 'San Francisco',
      tastingNotes: ['trigo', 'suave', 'limpio'],
    },
    {
      name: 'VODKA FIRE& ICE PREMIUM',
      brand: 'Fire & Ice',
      category: 'VODKA',
      description: 'Es un vodka premium de una calidad excepcional. Elaborado con ingredientes de alta calidad, trigo orgánico cuidadosamente seleccionado, agua alpina pura y destilación continua. Se utilizan filtros de platino para filtrar nuestro vodka.',
      presentation: '700 ml',
      alcoholicDegree: 40,
      price: 2400.00,
      currency: 'MXN',
      stock: 35,
      country: 'Estados Unidos',
      tastingNotes: ['trigo orgánico', 'agua alpina', 'puro'],
    },

    // LICORES Y APERITIVOS
    {
      name: 'BITTER CAMPARI',
      brand: 'Campari',
      category: 'LICOR',
      description: 'Es un licor a base de una infusión de hierbas amargas, plantas aromáticas y frutas en alcohol y agua. Tiene un color rojo vibrante con intenso aroma y sabor amargo distintivo. Perfecto para la preparación de cocteles como Negroni y Campari Orange.',
      presentation: '750 ml',
      alcoholicDegree: 28.5,
      price: 1400.00,
      currency: 'MXN',
      stock: 50,
      country: 'Italia',
      tastingNotes: ['amargo', 'hierbas', 'frutas'],
    },
    {
      name: 'APERITIVO APEROL',
      brand: 'Aperol',
      category: 'LICOR',
      description: 'Aperitivo de color naranja brillante y aroma ligero, a base de hierbas y naranja. Tiene un particular gusto delicadamente agrutado y amargo. Su signature drink es el Aperol Spritz, el coctel #1 de Italia.',
      presentation: '700 ml',
      alcoholicDegree: 11,
      price: 1200.00,
      currency: 'MXN',
      stock: 60,
      country: 'Italia',
      tastingNotes: ['naranja', 'hierbas', 'amargo', 'agradable'],
    },
    {
      name: 'LICOR FRANGELICO',
      brand: 'Frangelico',
      category: 'LICOR',
      description: 'Licor italiano hecho a base de avellanas silvestres tostadas sumergidas en alcohol junto con bayas y especias. El origen del licor es de más de 300 años, desde los primeros monjes cristianos que vivían en las colinas del norte de Italia.',
      presentation: '700 ml',
      alcoholicDegree: 24,
      price: 1600.00,
      currency: 'MXN',
      stock: 45,
      country: 'Italia',
      tastingNotes: ['avellanas', 'bayas', 'especias'],
    },

    // VERMOUTH
    {
      name: 'VERMOUTH CINZANO ROSSO',
      brand: 'Cinzano',
      category: 'VERMOUTH',
      description: 'Elaborado tras una combinación entre vinos, hierbas, especias y otros ingredientes naturales de todo el mundo especialmente seleccionados. Licor idealmente para preparar cocteles como: Negroni, Americano, Manhattan.',
      presentation: '750 ml',
      alcoholicDegree: 15,
      price: 900.00,
      currency: 'MXN',
      stock: 70,
      country: 'Italia',
      tastingNotes: ['hierbas', 'especias', 'vinos'],
    },

    // VINOS ESPUMOSOS
    {
      name: 'CINZANO GRAN DOLCE',
      brand: 'Cinzano',
      category: 'VINOS ESPUMOSOS',
      description: 'Vino espumante refrescante dulce y aromático que se crea a partir de las especialidades Muscato Blanco y Trebbiano. Es de cuerpo ligero que denota su frescor sabor agradable, con un acabado suave y placentero.',
      presentation: '750 ml',
      alcoholicDegree: 12,
      price: 800.00,
      currency: 'MXN',
      stock: 80,
      country: 'Italia',
      tastingNotes: ['dulce', 'aromático', 'fresco', 'suave'],
    },
    {
      name: 'CINZANO ROSE SWEET',
      brand: 'Cinzano',
      category: 'VINOS ESPUMOSOS',
      description: 'Vino espumante notas dulces y delicadas, elaborado en los viñedos más exclusivos de las colinas de Trevigiane, al norte de Italia.',
      presentation: '750 ml',
      alcoholicDegree: 12,
      price: 850.00,
      currency: 'MXN',
      stock: 75,
      country: 'Italia',
      region: 'Trevigiane',
      tastingNotes: ['dulce', 'delicado', 'frutal'],
    },
    {
      name: 'CINZANO TO SPRITZ',
      brand: 'Cinzano',
      category: 'VINOS ESPUMOSOS',
      description: 'Vino espumante aromático y seco de los viñedos más exclusivos de las Colinas de Trevigiane, al norte de Italia. Es un vino espumante joven, vivaz, delicado pero persistente. Espumante ideal para la preparación de Aperol Spritz.',
      presentation: '750 ml',
      alcoholicDegree: 12,
      price: 900.00,
      currency: 'MXN',
      stock: 70,
      country: 'Italia',
      region: 'Trevigiane',
      tastingNotes: ['seco', 'aromático', 'vivaz', 'delicado'],
    },

    // VINOS
    {
      name: 'VINO SANTA RITA TRES MEDALLAS CABERNET SAUVIGNON',
      brand: 'Santa Rita',
      category: 'VINO',
      description: 'Vinos varietales frescos, fáciles de tomar y de gran expresión frutal. Ideales para disfrutar día a día. Son vinos que conmemoran precisamente, las tres medallas otorgadas por el International Wines & Spirits Competition en la década de los ochenta.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 650.00,
      currency: 'MXN',
      stock: 100,
      country: 'Chile',
      tastingNotes: ['frutal', 'fresco', 'fácil'],
    },
    {
      name: 'VINO SANTA RITA TRES MEDALLAS MERLOT',
      brand: 'Santa Rita',
      category: 'VINO',
      description: 'Vinos varietales frescos, fáciles de tomar y de gran expresión frutal. Ideales para disfrutar día a día.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 650.00,
      currency: 'MXN',
      stock: 100,
      country: 'Chile',
      tastingNotes: ['frutal', 'fresco', 'suave'],
    },
    {
      name: 'VINO SANTA RITA TRES MEDALLAS CARMENERE',
      brand: 'Santa Rita',
      category: 'VINO',
      description: 'Vinos varietales frescos, fáciles de tomar y de gran expresión frutal. Ideales para disfrutar día a día.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 650.00,
      currency: 'MXN',
      stock: 100,
      country: 'Chile',
      tastingNotes: ['frutal', 'fresco', 'especiado'],
    },
    {
      name: 'VINO SANTA RITA TRES MEDALLAS SAUVIGNON BLANC',
      brand: 'Santa Rita',
      category: 'VINO',
      description: 'Vinos varietales frescos, fáciles de tomar y de gran expresión frutal. Ideales para disfrutar día a día.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 650.00,
      currency: 'MXN',
      stock: 100,
      country: 'Chile',
      tastingNotes: ['frutal', 'fresco', 'cítrico'],
    },
    {
      name: 'VINO 120 RESERVA ESPECIAL CABERNET SAUVIGNON',
      brand: '120 Reserva',
      category: 'VINO',
      description: 'Vinos Reserva fáciles de tomar y de gran expresión frutal. Ideales para disfrutar día a día. 120 es una marca con tradición e historia, existente para hacer el concepto del vino algo simple, genuino, abierto a una experiencia significante.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 850.00,
      currency: 'MXN',
      stock: 80,
      country: 'Chile',
      tastingNotes: ['frutal', 'fresco', 'reserva'],
    },
    {
      name: 'VINO SANTA RITA MEDALLA REAL GRAN RESERVA CABERNET SAUVIGNON',
      brand: 'Santa Rita',
      category: 'VINO',
      description: 'Vinos Reserva con cuerpo y carácter sutiles. Vinos con mucha expresión frutal y madera. Medalla Real nace en 1983 en honor a Francisco García Huidobro. Crianza de 14 meses en barricas considerando un 20% de barricas nuevas.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 1800.00,
      currency: 'MXN',
      stock: 40,
      country: 'Chile',
      tastingNotes: ['frutal', 'madera', 'cuerpo', 'barrica'],
    },
    {
      name: 'VINO SANTA RITA CASA REAL',
      brand: 'Santa Rita',
      category: 'VINO',
      description: 'Vino de alta gama, uvas cuidadosamente seleccionadas y cosechadas a mano desde sus excepcionales viñedos de más de 20 años de antigüedad. Son vinos complejos y concentrados, que poseen un estilo clásico y elegante.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 3500.00,
      currency: 'MXN',
      stock: 20,
      country: 'Chile',
      tastingNotes: ['complejo', 'concentrado', 'elegante', 'clásico'],
    },
    {
      name: 'VINO MAIPO CLASSIC SERIES CABERNET SAUVIGNON',
      brand: 'Maipo',
      category: 'VINO',
      description: 'Vinos frescos, fáciles de tomar y de gran expresión frutal. Ideales para disfrutar día a día.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 700.00,
      currency: 'MXN',
      stock: 90,
      country: 'Chile',
      tastingNotes: ['frutal', 'fresco', 'fácil'],
    },
    {
      name: 'VINO MAIPO SWEET BLANCO',
      brand: 'Maipo',
      category: 'VINO',
      description: 'Vinos frescos y balanceados, fáciles de tomar con una acidez nítida y que dejan un leve sabor dulce en boca.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 750.00,
      currency: 'MXN',
      stock: 85,
      country: 'Chile',
      tastingNotes: ['dulce', 'fresco', 'balanceado', 'acidez'],
    },
    {
      name: 'SANGRIA MAIPO TINTO',
      brand: 'Maipo',
      category: 'VINO',
      description: 'Es una sangría elaborada 100% con vino tinto, de origen chileno. Se caracteriza por su color rojo brillante y atractivas notas cítricas y de manzana. Posee un sabor potente y frutal, balanceado y fresco, con tenues notas especiadas.',
      presentation: '750 ml',
      alcoholicDegree: 8,
      price: 600.00,
      currency: 'MXN',
      stock: 100,
      country: 'Chile',
      tastingNotes: ['cítrico', 'manzana', 'frutal', 'especiado'],
    },
    {
      name: 'VINO AVES DEL SUR VARIETAL CABERNET SAUVIGNON',
      brand: 'Aves del Sur',
      category: 'VINO',
      description: 'Estos vinos proceden de viñedos que han sido acondicionados para producir fruta de la más alta calidad. El sabor fresco y el carácter noble de estos vinos, los hacen consistentes y listos para su consumo.',
      presentation: '750 ml',
      alcoholicDegree: 12.5,
      price: 550.00,
      currency: 'MXN',
      stock: 120,
      country: 'Chile',
      tastingNotes: ['frutal', 'fresco', 'noble'],
    },
    {
      name: 'VINO PRISTINA TINTO',
      brand: 'Pristina',
      category: 'VINO',
      description: 'Vino de origen Español, equilibrado y armónico con notas frutales frescas. Se recomienda servir entre 12 y 14 grados centígrados. Ideal para acompañar con carnes, arroz y paté. Tiene notas persistentes y prolongadas, muy equilibrado y fácil de beber.',
      presentation: '1500 ml',
      alcoholicDegree: 12.5,
      price: 900.00,
      currency: 'MXN',
      stock: 60,
      country: 'España',
      tastingNotes: ['frutal', 'fresco', 'equilibrado', 'armónico'],
    },

    // PREMEZCLADOS
    {
      name: 'PREMEZCLADOS MG SPIRIT VODKA BLUEBERRY',
      brand: 'MG Spirit',
      category: 'PREMEZCLADO',
      description: 'Producto del combinado ideal de bebida espirituosa, con la mayor variedad de sabores. MG Spirit es un producto elaborado con ingredientes de la más alta calidad, seleccionados de sus destilerías ubicadas en Barcelona, España.',
      presentation: '275 ml',
      alcoholicDegree: 5.5,
      price: 180.00,
      currency: 'MXN',
      stock: 200,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['blueberry', 'dulce', 'frutal'],
    },
    {
      name: 'PREMEZCLADOS MG SPIRIT VODKA PIÑA',
      brand: 'MG Spirit',
      category: 'PREMEZCLADO',
      description: 'Producto del combinado ideal de bebida espirituosa, con la mayor variedad de sabores. MG Spirit es un producto elaborado con ingredientes de la más alta calidad.',
      presentation: '275 ml',
      alcoholicDegree: 5.5,
      price: 180.00,
      currency: 'MXN',
      stock: 200,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['piña', 'dulce', 'tropical'],
    },
    {
      name: 'PREMEZCLADOS MG SPIRIT VODKA NARANJA',
      brand: 'MG Spirit',
      category: 'PREMEZCLADO',
      description: 'Producto del combinado ideal de bebida espirituosa, con la mayor variedad de sabores. MG Spirit es un producto elaborado con ingredientes de la más alta calidad.',
      presentation: '275 ml',
      alcoholicDegree: 5.5,
      price: 180.00,
      currency: 'MXN',
      stock: 200,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['naranja', 'cítrico', 'dulce'],
    },
    {
      name: 'PREMEZCLADOS MG SPIRIT VODKA LIMÓN',
      brand: 'MG Spirit',
      category: 'PREMEZCLADO',
      description: 'Producto del combinado ideal de bebida espirituosa, con la mayor variedad de sabores. MG Spirit es un producto elaborado con ingredientes de la más alta calidad.',
      presentation: '275 ml',
      alcoholicDegree: 5.5,
      price: 180.00,
      currency: 'MXN',
      stock: 200,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['limón', 'cítrico', 'refrescante'],
    },
    {
      name: 'PREMEZCLADOS MG SPIRIT MOJITO',
      brand: 'MG Spirit',
      category: 'PREMEZCLADO',
      description: 'Producto del combinado ideal de bebida espirituosa, con la mayor variedad de sabores. MG Spirit es un producto elaborado con ingredientes de la más alta calidad.',
      presentation: '275 ml',
      alcoholicDegree: 5.5,
      price: 180.00,
      currency: 'MXN',
      stock: 200,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['menta', 'limón', 'refrescante'],
    },
    {
      name: 'PREMEZCLADOS MG SPIRIT VODKA MARACUYÁ',
      brand: 'MG Spirit',
      category: 'PREMEZCLADO',
      description: 'Producto del combinado ideal de bebida espirituosa, con la mayor variedad de sabores. MG Spirit es un producto elaborado con ingredientes de la más alta calidad.',
      presentation: '275 ml',
      alcoholicDegree: 5.5,
      price: 180.00,
      currency: 'MXN',
      stock: 200,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['maracuyá', 'tropical', 'dulce'],
    },
    {
      name: 'PREMEZCLADOS MG SPIRIT VODKA MANZANA',
      brand: 'MG Spirit',
      category: 'PREMEZCLADO',
      description: 'Producto del combinado ideal de bebida espirituosa, con la mayor variedad de sabores. MG Spirit es un producto elaborado con ingredientes de la más alta calidad.',
      presentation: '275 ml',
      alcoholicDegree: 5.5,
      price: 180.00,
      currency: 'MXN',
      stock: 200,
      country: 'España',
      region: 'Barcelona',
      tastingNotes: ['manzana', 'dulce', 'frutal'],
    },
  ];

  // Insertar productos con imágenes
  console.log(`📦 Inserting ${products.length} products with images...`);

  for (const product of products) {
    await prisma.product.create({
      data: {
        name: product.name,
        slug: generateSlug(product.name),
        brand: product.brand,
        category: product.category,
        description: product.description,
        presentation: product.presentation,
        alcoholicDegree: product.alcoholicDegree,
        price: product.price,
        currency: product.currency,
        stock: product.stock,
        country: product.country,
        region: product.region,
        tastingNotes: product.tastingNotes,
        imageUrl: categoryImages[product.category], // ← IMAGEN AGREGADA
        isActive: true,
      },
    });
  }

  console.log('✅ Products inserted successfully with images');

  // Crear usuario admin de prueba
  await prisma.user.create({
    data: {
      email: 'admin@gws.com',
      passwordHash: 'hashed_password_placeholder',
      role: 'ADMIN',
      firstName: 'Admin',
      lastName: 'GWS',
    },
  });

  console.log('👤 Admin user created');
  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });